# Generated by Django 4.2.20 on 2025-04-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_is_verified_user_registration_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='category',
            new_name='course_unit',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='description',
            new_name='issue_details',
        ),
        migrations.AddField(
            model_name='issue',
            name='lecturer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', 'Semester 1'), ('2', 'Semester 2')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
